import { Photo, DogOfTheMonth, FunFact, CareTip, DogQuote } from './types';

export const photos: Photo[] = [
  {
    id: 1,
    title: 'Golden Retriever',
    url: '/images/dog-golden-retriever.jpg',
    category: 'Sporting Group',
    description: 'Known for their friendly, gentle temperament and radiant golden coats, Golden Retrievers are intelligent, devoted companions that excel as family pets, therapy dogs, and joyful outdoor adventure partners.',
    traits: ['Friendly & Eager to Please', 'Intelligent & Trainable', 'Gentle with Kids', 'Playful Swimmer'],
    favoriteSnack: 'Crispy sweet apple slices & peanut butter dollops',
    funQuirk: 'Must carry a toy or sock in their mouth to greet anyone entering the house',
    energyLevel: 'High (Needs Daily Play)',
    lifespan: '10 - 12 Years',
  },
  {
    id: 2,
    title: 'Pembroke Welsh Corgi',
    url: '/images/dog-pembroke-corgi.jpg',
    category: 'Herding Group',
    description: 'With their signature upright ears, cheerful smiles, and sturdy low-set bodies, Pembroke Welsh Corgis are affectionate, high-spirited, and remarkably bright dogs originally bred in Wales to herd livestock.',
    traits: ['Affectionate & Loyal', 'High-Spirited & Bold', 'Clever Problem Solver', 'Vigilant Watchpup'],
    favoriteSnack: 'Baby carrots & crunchy dehydrated beef liver',
    funQuirk: 'Does the iconic "sploot" with back legs stretched straight out behind them',
    energyLevel: 'Medium-High (Playful Bursts)',
    lifespan: '12 - 13 Years',
  },
  {
    id: 3,
    title: 'Siberian Husky',
    url: '/images/dog-siberian-husky.jpg',
    category: 'Working Group',
    description: 'Celebrated for their striking arctic beauty, piercing eyes, and boundless stamina, Siberian Huskies are vocal, athletic pack animals built for long-distance cold-weather sled expeditions.',
    traits: ['Outgoing & Friendly', 'Dramatically Vocal', 'Endless Athletic Stamina', 'Free-Spirited Explorer'],
    favoriteSnack: 'Frozen salmon skin cubes & blueberry popsicles',
    funQuirk: 'Holds full dramatic singing conversations with wholehearted howling',
    energyLevel: 'Very High (Marathon Runner)',
    lifespan: '12 - 14 Years',
  },
  {
    id: 4,
    title: 'French Bulldog',
    url: '/images/dog-french-bulldog.jpg',
    category: 'Non-Sporting Group',
    description: 'Featuring distinctive bat-shaped ears, compact muscular builds, and irresistible wrinkled snouts, Frenchies are affectionate, comical housemates that thrive on companionship and cozy cuddles.',
    traits: ['Playful & Comedic', 'Affectionate Lapdog', 'Adaptable & Easygoing', 'Charming Companion'],
    favoriteSnack: 'Freeze-dried chicken bites & mashed sweet potato',
    funQuirk: 'Snores gently like a tiny contented outboard motor when snuggling',
    energyLevel: 'Low-Medium (Couch Cuddler)',
    lifespan: '10 - 12 Years',
  },
  {
    id: 5,
    title: 'Beagle',
    url: '/images/dog-beagle.jpg',
    category: 'Hound Group',
    description: 'With soulful hazel eyes and legendary scent-tracking prowess, Beagles are gentle, merry hounds adored for their curious nature, loyal pack loyalty, and happy tail-wags.',
    traits: ['Curious & Inquisitive', 'Merry & Friendly', 'Determined Scent Hound', 'Gentle Companion'],
    favoriteSnack: 'String cheese nibbles & roasted sweet potatoes',
    funQuirk: 'Will stop in their tracks and let out a signature melodious bay when tracking a squirrel',
    energyLevel: 'Medium-High (Scent-Driven)',
    lifespan: '12 - 15 Years',
  },
  {
    id: 6,
    title: 'Shiba Inu',
    url: '/images/dog-shiba-inu.jpg',
    category: 'Non-Sporting Group',
    description: 'An ancient Japanese breed famed for spirited independence, plush golden coats, and fox-like attentiveness. Shibas are fastidious, clever, and deeply devoted to their trusted humans.',
    traits: ['Alert & Attentive', 'Spirited & Confident', 'Fastidiously Clean', 'Fiercely Loyal'],
    favoriteSnack: 'Crispy roasted salmon bites & pumpkin puree treats',
    funQuirk: 'Grooms their paws meticulously like a cat after every outdoor walk',
    energyLevel: 'Medium (Alert & Agile)',
    lifespan: '13 - 16 Years',
  },
  {
    id: 7,
    title: 'Samoyed',
    url: '/images/dog-samoyed.jpg',
    category: 'Working Group',
    description: 'Nicknamed the "Smiling Sammy" for their perpetually cheerful upturned lips and brilliant white cloud-like coats, Samoyeds are gentle, warm-hearted northern working dogs that adore people of all ages.',
    traits: ['Friendly "Sammy Smile"', 'Gentle with Children', 'Social & Warm-Hearted', 'Thick Cloud Coat'],
    favoriteSnack: 'Cold watermelon chunks & roasted turkey tidbits',
    funQuirk: 'Their black mouth corners curve upward to prevent icicles from forming on their lips',
    energyLevel: 'High (Snow Lover)',
    lifespan: '12 - 14 Years',
  },
  {
    id: 8,
    title: 'Dachshund',
    url: '/images/dog-dachshund.jpg',
    category: 'Hound Group',
    description: 'Affectionately known as "wiener dogs" for their iconic long silhouettes and short legs, Dachshunds are spunky, fearless hounds packed with big personality and tenacious curiosity.',
    traits: ['Clever & Tenacious', 'Spunky & Courageous', 'Affectionate Burrower', 'Alert Watcher'],
    favoriteSnack: 'Steamed green beans & freeze-dried beef tendon chews',
    funQuirk: 'Burrows like a mole completely underneath blankets until only their wet nose peeks out',
    energyLevel: 'Medium (Spunky Explorer)',
    lifespan: '12 - 16 Years',
  },
  {
    id: 9,
    title: 'Pug',
    url: '/images/dog-pug.jpg',
    category: 'Toy Group',
    description: 'Embodying their ancient motto "multum in parvo" (a lot in a little), Pugs are wrinkly-faced charmers known for playful comedic antics, expressive eyes, and immense loyalty.',
    traits: ['Charming Clown', 'Loving & Loyal', 'Even-Tempered', 'Expressive Head-Tilter'],
    favoriteSnack: 'Banana slices & crunchy baked oat and honey biscuits',
    funQuirk: 'Tilts head 90 degrees with intense curiosity whenever you ask "Wanna go for a walk?"',
    energyLevel: 'Low-Medium (Professional Nap Taker)',
    lifespan: '13 - 15 Years',
  },
];

export const dogOfTheMonth: DogOfTheMonth = {
  name: 'Milo',
  breed: 'Golden Retriever Pup',
  age: '4 Months Old',
  month: 'September Spotlight',
  badge: '🏆 Pup of the Month',
  url: '/images/puppy-spotlight.jpg',
  bio: 'Meet Milo! A bundle of golden fluff who loves chasing autumn leaves, mastering the gentle paw-shake, and napping belly-up in warm patches of sunlight.',
  favSnack: 'Crispy sweet apple slices & peanut butter',
  superpower: 'Instantly melting hearts in 3 seconds flat',
  bestTrick: 'High-five & synchronized tail-wag',
  relatedDogId: 1,
};

export const funFacts: FunFact[] = [
  {
    id: 1,
    category: 'Super Senses',
    fact: 'A dog’s sense of smell is up to 100,000 times more sensitive than a human’s! They have more than 300 million olfactory receptors in their noses compared to our 6 million.',
    icon: '👃',
  },
  {
    id: 2,
    category: 'Unique Anatomy',
    fact: 'Just like human fingerprints, every dog has a completely unique nose print with distinct ridges and creases that can uniquely identify them.',
    icon: '🐾',
  },
  {
    id: 3,
    category: 'Dream Land',
    fact: 'Dogs experience REM sleep and dream just like humans! The gentle twitching of paws and soft muted woofs during sleep indicate they are reliving daily playtime adventures.',
    icon: '💤',
  },
  {
    id: 4,
    category: 'Tail Language',
    fact: 'When a dog wags their tail more to their right side, research shows they are experiencing positive, affectionate emotions. A wag to the left can indicate caution or uncertainty.',
    icon: '✨',
  },
  {
    id: 5,
    category: 'Super Hearing',
    fact: 'Dogs can hear frequencies nearly twice as high as humans (up to 45,000 Hz). Plus, their ears have 18 specialized muscles to rotate and funnel sounds like miniature radar dishes.',
    icon: '👂',
  },
  {
    id: 6,
    category: 'Puppy Magic',
    fact: 'Puppies are born without teeth and are deaf and blind for their first two weeks. Their sense of touch and smell guides them directly to their mother’s warm embrace.',
    icon: '🍼',
  },
];

export const careTips: CareTip[] = [
  {
    id: 1,
    badge: 'Hydration & Diet',
    title: 'Keep Cool Water Plentiful',
    category: 'Wellness',
    tip: 'Puppies and adult dogs lose moisture quickly when active. Provide fresh, clean water bowls in multiple spots around your home and wash the bowls daily.',
  },
  {
    id: 2,
    badge: 'Mental Health',
    title: 'The Power of "Sniffaris"',
    category: 'Enrichment',
    tip: 'Sniffing provides profound mental stimulation that burns as much energy as a brisk run. Give your pup time to pause and investigate scents on walks to boost confidence and reduce stress.',
  },
  {
    id: 3,
    badge: 'Teething & Chews',
    title: 'Safe Chewing Outlets',
    category: 'Puppy Care',
    tip: 'Puppy teeth erupt between 3 to 6 months old. Chilled natural rubber toys, frozen damp washcloths, and puppy-safe teething rings soothe inflamed gums and save your shoes!',
  },
  {
    id: 4,
    badge: 'Socialization',
    title: 'Positive, Low-Stress Exposures',
    category: 'Training',
    tip: 'Introduce puppies to various textures (grass, hardwood, rugs), gentle household sounds (vacuum at distance), and new friends paired with generous praise and wholesome treats.',
  },
  {
    id: 5,
    badge: 'Rest & Recovery',
    title: 'Honor Their Sleep Needs',
    category: 'Routine',
    tip: 'Growing puppies need 18 to 20 hours of sleep per day for cognitive development and immune health. Ensure an undisturbed, cozy den or crate where they can sleep peacefully.',
  },
];

export const dogQuotes: DogQuote[] = [
  {
    id: 1,
    quote: 'A dog is the only thing on earth that loves you more than he loves himself.',
    author: 'Josh Billings',
  },
  {
    id: 2,
    quote: 'Happiness is a warm puppy.',
    author: 'Charles M. Schulz',
  },
  {
    id: 3,
    quote: 'The world would be a nicer place if everyone had the ability to love as unconditionally as a dog.',
    author: 'M.K. Clinton',
  },
  {
    id: 4,
    quote: 'Dogs do speak, but only to those who know how to listen.',
    author: 'Orhan Pamuk',
  },
  {
    id: 5,
    quote: 'No matter how little money and how few possessions you own, having a dog makes you rich.',
    author: 'Louis Sabin',
  },
  {
    id: 6,
    quote: 'Dogs have a way of finding the people who need them, and filling an emptiness we didn’t even know we had.',
    author: 'Thom Jones',
  },
];

